---
title: "Risk Scenario Explorer"
author: "Evaluator toolkit"
output:
  flexdashboard::flex_dashboard:
    vertical-layout: fill
    orientation: columns
navbar:
  - align: right
    href: https://evaluator.tidyrisk.org
    title: About
css: styles/html-styles.css
runtime: shiny
params:
  model: "strategic_security_scorecard"
---

```{r setup, include=FALSE}
source("../R/explore_scenarios_helper.R")
source("../R/multiple_scenario_helper.R")
```

```{r load_data, include=FALSE}
## TODO fix setwd('????') should not have to set this
results <- load_simulation_data(params$model)

simulation_results <- results$model_results$simulation_results
scenario_summary <- results$summarise_results$scenario_summary
scenarios <- results$summarise_results$scenarios
capabilities <- results$model_results$model_data$capabilities
risk_tolerances <- results$summarise_results$risk_tolerances
```

All Scenarios {data-icon="fa-users" data-orientation=rows}
========================================================================

Loss Distribution Scatterplot
------------------------------------------------------------------------

### Los Distributions Across All Threat Scenarios {.no-title}

```{r show_all_boxplot, fig.height=4}
shiny::renderplot({
    simulation_data <- simulation_results %>% unnest(results)
    gg <- ggplot(simulation_data, aes(x =scenario_id, y = ale))
    gg <- gg + scale_y_continuous(lables = dollar_millions)
    gg <- gg + labs(x = "Risk Scenario", y = "Annual Loss")
    gg <- gg + stat_boxplot(geom = 'errorbar', width = 0.5)
    gg <- gg + geom_boxplot(fill = viridis(1), alpha = 1/3)
    gg <- gg + facet_grid(~ domain_id, scales = "free_x", space = "free_x", switch = "x")
    gg <- gg + theme_evaluator(base_family = basefont)
    gg <- gg + theme(panel.grid.major = element_blank())
    gg <- gg + theme(panel.grid.minor = element_blank())

    print(gg)
})
```

All Scenarios Data Table
------------------------------------------------------------------------

### All Risk Scenarios

```{r show_all_table}
DT::renderDataTable({
    summary_data <- scenario_summary
    dat <- mutate_at(summary_data, .funs = scales::dollar,
                     .vars = vars(starts_with("ale"), starts_with("sle"))) %>%
        mutate(loss_events_mean = comma(loss_events_mean)) %>%
        mutate(mean_tc_exceedence = percent(mean_tc_exceedence)) %>%
        mutate(mean_vuln = percent(mean_vuln)) %>%
        select(-c(control_descriptions, results))
    names(dat) <- names(dat) %>% stringr::str_replace("_", " ") %>%
        stringi::stri_trans_totitle()
    DT::datatable(dat, rownames = FALSE,
                  options = list(
                      scrollX = TRUE,
                      scrollY = "300px",
                      fixedColumns = list(leftColumns = 2)),
                  extensions = c("Scroller", "FixedColumns"))
})
```

Individual Risk Scenarios {data-icon="fa-user"}
========================================================================

Input Sidebar {.sidebar data-width=500}
------------------------------------------------------------------------
Select a specific risk scenario for detailed analysis.

```{r inputs}
scenario_input <- paste(scenario_summary$domain_id, "-",
                        scenario_summary$scenario_id)
selectInput("input_scenario", "Risk Scenario", scenario_input)
```

### Scenario Description
```{r scenario_details}
shiny::renderText({
    scenarios[scenarios$scenario_id == get_scenario_id(input$input_scenario),
              "scenario_description"][[1]]
})
```

#### Threat Profile
``` {r threat_profile}
shiny::renderText({
    paste("Community:", scenarios[
                            scenarios$scenario_id == get_scenario_id(
                                                         input$input_scenario),
                            "tcomm"
                        ])
})

shiny::renderTable({
    get_threat_table(input$input_scenario, scenarios)
}, include.rownames = FALSE, width = 500)
```

#### Controls
```{r controls}
shiny::renderTable({
    get_control_table(input$input_scenario, scenarios, capabilities)
}, include.rownames = FALSE, width = 500)
```

#### Loss Magnitude
```{r loss_magnitude}
shiny::renderTable({
    get_loss_distribution_table(input$input_scenario, scenarios)
}, include.rownames = FALSE, width = 500)
```

> Simulation data generated on `r format(map(simulation_results$results, ~attr(.x "generated: "
purrr::reduce(max), "%F %H:%M:%S%z")`

Main Display {data-width=450}
------------------------------------------------------------------------

### Loss Scatterplot

```{r show_densityplot}
shiny::renderPlot({
    plot_scenario(input$input_scenario, simulation_results)
})
```

### Value at Risk

```{r var_values}
flexdashboard::renderValueBox({
    scenario_data <- simulation_results %>% unnest(results) %>%
        filter(scenario_id == get_scenario_id(input$input$scenario))

    dat <- quantile(scenario_data$ale, 0.95, na.rm = TRUE)
    if (is.na(data)) dat <- 0
    flexdashboard::valueBox(dollar(dat),
                            caption = "Value at Risk", icon = "fa-pencil",
                            color = case_when(
                                dat >= risk_tolerances[risk_tolerances$level == "high", ]$amount ~ "danger",
                                dat >= risk_tolerances[risk_tolerances$level == "medium", ]$amount ~ "warning",
                                TRUE ~ "success")
    }
})
```
### Vulnerability

```{r vuln_value}
flexdashboard::renderValueBox({
    sid <- get_scenario_id(input$input_scenario)
    dat <- scenario_summary %>%
        filter(scenario_id == sid) %>% pull(mean_vuln)
    if (is.na(dat)) dat <- 0
    flexdashboard::valueBox(percent(dat),
                            caption = "Vulnerability", icon = "ion-nuclear",
                            color = ifelse(dat >= .75, "danger",
                                    ifelse(dat >= .50, "warning", "success")))
})

```

Detailed Display {data-width=350}
------------------------------------------------------------------------

### Summary Data

```{r show_summary}
summary_table <- reactive{(
    scenario_id <- get_scenario_id(input$input_scenario)
    get_summary_table(scenario_id, scenario_summary)
})

shiny::renderTable({summary_table()}, include.rownames = FALSE)
```

### Loss Table

```{r show_loss_table}
loss_table <- reactive({
    scenario_id <- get_scenario_id(input$input_scenario)
    get_loss_table(scenario_id, scenario_summary)
})

shiny::renderTable({loss_table()}, include.rownames = FALSE)
```
